### ISSUE TITLE
What version of potrace is this for?

### ISSUE THREAD

**Issue by ays0110** [kennyp/potracer#1]
I brew installed potrace v 1.12
When I try to gem install potracer, I get: ERROR:  Error installing potracer:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150607-1841-gr3065.rb extconf.rb
```

checking for potracelib.h... yes
checking for potrace_version() in -lpotrace... no
lib potrace not found
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    --with-potrace-dir
    --without-potrace-dir
    --with-potrace-include
    --without-potrace-include=${potrace-dir}/include
    --with-potrace-lib
    --without-potrace-lib=${potrace-dir}/
    --with-potracelib
    --without-potracelib

extconf failed, exit code 1

**Comment by kennyp** [comment]
Hi there. It should work fine with potrace 1.12, that's what I'm running on my box. It appears that it's not able to locate where homebrew installed libpotrace. It checks `/opt/local/lib`, `/user/local/lib`, `/usr/lib`. It will also check the libdir/includedir given on the command line.
