### ISSUE TITLE
ERROR lib potrace not found

### ISSUE THREAD

**Issue by franciscoandres** [kennyp/potracer#2]
Hi kennyp, hope you doing well despite covid

I am getting an error after install your gem

I am using: Ubuntu 18.04 LTS, Ruby 2.5.1, potrace 1.15

`current directory: /home/frank/.rvm/gems/ruby-2.5.1/gems/potracer-1.1.4/ext/potracer
/home/frank/.rvm/rubies/ruby-2.5.1/bin/ruby -I /home/frank/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0 -r ./siteconf20200621-31322-1ofzm36.rb
extconf.rb
checking for potracelib.h... yes
checking for potrace_version() in -lpotrace... no
lib potrace not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
`

and checking the mkmf.log show me this:

`find_header: checking for potracelib.h... -------------------- yes

"gcc -o conftest -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/backward -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0 -I. -I/opt/local/include -I/usr/local/include -I/home/frank/.rvm/rubies/ruby-2.5.1/include -I/usr/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict  -fPIC conftest.c  -L. -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/opt/local/lib -Wl,-rpath,/opt/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/usr/lib -Wl,-rpath,/usr/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -E -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/backward -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0 -I. -I/opt/local/include -I/usr/local/include -I/home/frank/.rvm/rubies/ruby-2.5.1/include -I/usr/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <potracelib.h>
/* end */

--------------------

find_library: checking for potrace_version() in -lpotrace... -------------------- no

"gcc -o conftest -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/backward -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0 -I. -I/opt/local/include -I/usr/local/include -I/home/frank/.rvm/rubies/ruby-2.5.1/include -I/usr/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict  -fPIC conftest.c  -L. -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/opt/local/lib -Wl,-rpath,/opt/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/usr/lib -Wl,-rpath,/usr/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby -lpotrace  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:13:57: error: ‘potrace_version’ undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))potrace_version; return !p; }
                                                         ^~~~~~~~~~~~~~~
conftest.c:13:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))potrace_version; return !p; }
/* end */

"gcc -o conftest -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0/ruby/backward -I/home/frank/.rvm/rubies/ruby-2.5.1/include/ruby-2.5.0 -I. -I/opt/local/include -I/usr/local/include -I/home/frank/.rvm/rubies/ruby-2.5.1/include -I/usr/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict  -fPIC conftest.c  -L. -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/opt/local/lib -Wl,-rpath,/opt/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L/home/frank/.rvm/rubies/ruby-2.5.1/lib -Wl,-rpath,/home/frank/.rvm/rubies/ruby-2.5.1/lib -L/usr/lib -Wl,-rpath,/usr/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby -lpotrace  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -lpotrace
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void potrace_version();
14: int t(void) { potrace_version(); return 0; }
/* end */

--------------------`

is there any solution for this? thank you really appreciate the help

**Comment by kennyp** [comment]
Hey @franciscoandres, I'm on Ubuntu 18 LTS as well. Do you have both `libpotrace0` and `libpotrace-dev` installed? Looking at the trace you posted it may be that it's finding the `.h` file but not the `.so` file.

**Comment by franciscoandres** [comment]
Hey @kennyp thank you for the quick response, yes it works!!! thank you :)
